#!/usr/bin/python

import sys
import subprocess
import argparse

parser = argparse.ArgumentParser(prog='git msg-prefix')

subparsers = parser.add_subparsers(title='Commands')
listParser = subparsers.add_parser('list', help='List all prefixes')
listParser.set_defaults(which='list')

setParser = subparsers.add_parser('set', help='Set prefix for commit message')
setParser.set_defaults(which='set')
setParser.add_argument('prefix', help='String which will be included in all commit messages for specific branch')
setParser.add_argument('-b', '--branch', help='Branch name (default is current branch)', required=False)

args = parser.parse_args()