#!/usr/bin/python

import argparse
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/command')
from command import Command

parser = argparse.ArgumentParser(prog='git msg-prefix')

subparsers = parser.add_subparsers(title='Commands')
listParser = subparsers.add_parser('list', help='List all prefixes')
listParser.set_defaults(which='ListCommand')

setParser = subparsers.add_parser('set', help='Set prefix for commit message')
setParser.set_defaults(which='SetCommand')
setParser.add_argument('prefix', help='String which will be included in all commit messages for specific branch')
setParser.add_argument('branch', help='Branch name (default is current branch)', nargs='?')

removeParser = subparsers.add_parser('remove', help='Set prefix for commit message')
removeParser.set_defaults(which='RemoveCommand')
removeParser.add_argument('branch', help='Branch name (default is current branch)', nargs='?')

args = parser.parse_args()

command = Command(args)
command.run()